// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticlesDocumentDataSlicesSlice =
  | PurchaseSlice
  | SocialLinksSlice
  | GalleryLinkSlice
  | AuthorsSlice
  | SingleButtonSlice
  | VideoSlice
  | QuoteSlice
  | SetlistSlice
  | ImageSlice
  | RichTextSlice
  | CarouselSlice;

type ArticlesDocumentDataSlices1Slice = LinksSlice;

/**
 * Content for Articles documents
 */
interface ArticlesDocumentData {
  /**
   * Title field in *Articles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Articles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Type field in *Articles*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Live report
   * - **API ID Path**: articles.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<
    | "Live report"
    | "Press release"
    | "Interview"
    | "Discovery"
    | "Gallery"
    | "Other",
    "filled"
  >;

  /**
   * Featured Image field in *Articles*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Group/Idol field in *Articles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.idol_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  idol_name: prismic.KeyTextField;

  /**
   * Venue field in *Articles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.venue
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  venue: prismic.KeyTextField;

  /**
   * Event date field in *Articles*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.event_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  event_date: prismic.DateField;

  /**
   * Publication date field in *Articles*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.publication_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publication_date: prismic.DateField;

  /**
   * Author field in *Articles*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"author">;

  /**
   * Gallery Link field in *Articles*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.gallery_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  gallery_link: prismic.ContentRelationshipField<"gallery">;

  /**
   * Slice Zone field in *Articles*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticlesDocumentDataSlicesSlice> /**
   * Meta Title field in *Articles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: articles.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Articles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: articles.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Articles*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Articles*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.slices1[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<ArticlesDocumentDataSlices1Slice>;
}

/**
 * Articles document from Prismic
 *
 * - **API ID**: `articles`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticlesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticlesDocumentData>,
    "articles",
    Lang
  >;

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * Display order field in *Author*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: author.display_order
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  display_order: prismic.NumberField;

  /**
   * Name field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Profile picture field in *Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.profile_picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_picture: prismic.ImageField<never>;

  /**
   * Specialization field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.specialization
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  specialization: prismic.KeyTextField;

  /**
   * Description field in *Author*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Twitter field in *Author*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: author.twitter
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  twitter: prismic.LinkField;

  /**
   * Instagram field in *Author*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: author.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;

  /**
   * Website field in *Author*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: author.website
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  website: prismic.LinkField;
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;

/**
 * Item in *Gallery → Gallery*
 */
export interface GalleryDocumentDataGalleryItem {
  /**
   * Image field in *Gallery → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.gallery[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type GalleryDocumentDataSlicesSlice = never;

/**
 * Content for Gallery documents
 */
interface GalleryDocumentData {
  /**
   * Type field in *Gallery*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Gallery
   * - **API ID Path**: gallery.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Gallery" | "Other", "filled">;

  /**
   * Title field in *Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Featured image field in *Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Artist name field in *Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.artist_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  artist_name: prismic.KeyTextField;

  /**
   * Event date field in *Gallery*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.event_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  event_date: prismic.DateField;

  /**
   * Venue field in *Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.venue
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  venue: prismic.KeyTextField;

  /**
   * Official photos? field in *Gallery*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: gallery.is_official_photos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_official_photos: prismic.BooleanField;

  /**
   * Photographer field in *Gallery*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.photographer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  photographer: prismic.ContentRelationshipField<"author">;

  /**
   * Gallery field in *Gallery*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<GalleryDocumentDataGalleryItem>>;

  /**
   * Slice Zone field in *Gallery*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GalleryDocumentDataSlicesSlice> /**
   * Meta Title field in *Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: gallery.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: gallery.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Gallery document from Prismic
 *
 * - **API ID**: `gallery`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<GalleryDocumentData>,
    "gallery",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = TaglistSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Background field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.background
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ImageGridSlice
  | ImageListSlice
  | SetlistSlice
  | TaglistSlice
  | SocialLinksSlice
  | PurchaseSlice
  | AuthorsSlice
  | VideoSlice
  | QuoteSlice
  | DocListSlice
  | GallerySlice
  | SingleButtonSlice
  | RichTextSlice
  | CarouselSlice
  | ImageSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Type field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Live reports
   * - **API ID Path**: page.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<
    "Live reports" | "Discoveries" | "Press Releases" | "Galleries" | "Other",
    "filled"
  >;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | ArticlesDocument
  | AuthorDocument
  | GalleryDocument
  | HomepageDocument
  | PageDocument;

/**
 * Primary content in *Authors → Default → Primary*
 */
export interface AuthorsSliceDefaultPrimary {
  /**
   * Author field in *Authors → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: authors.default.primary.author
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"author">;

  /**
   * Official photos? field in *Authors → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: authors.default.primary.official_photos
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  official_photos: prismic.BooleanField;

  /**
   * Photographer field in *Authors → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: authors.default.primary.photographer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  photographer: prismic.ContentRelationshipField<"author">;

  /**
   * Translator - JP field in *Authors → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: authors.default.primary.translator_jp
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  translator_jp: prismic.ContentRelationshipField<"author">;

  /**
   * Translator - EN field in *Authors → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: authors.default.primary.translator_en
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  translator_en: prismic.ContentRelationshipField<"author">;

  /**
   * Translator - FR field in *Authors → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: authors.default.primary.translator_fr
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  translator_fr: prismic.ContentRelationshipField<"author">;
}

/**
 * Default variation for Authors Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AuthorsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AuthorsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Authors*
 */
type AuthorsSliceVariation = AuthorsSliceDefault;

/**
 * Authors Shared Slice
 *
 * - **API ID**: `authors`
 * - **Description**: Authors
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AuthorsSlice = prismic.SharedSlice<
  "authors",
  AuthorsSliceVariation
>;

/**
 * Item in *Carousel → Default → Primary → Slides*
 */
export interface CarouselSliceDefaultPrimarySlidesItem {
  /**
   * Image field in *Carousel → Default → Primary → Slides*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.slides[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Carousel → Default → Primary*
 */
export interface CarouselSliceDefaultPrimary {
  /**
   * Slides field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.slides[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  slides: prismic.GroupField<Simplify<CarouselSliceDefaultPrimarySlidesItem>>;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Primary content in *DocList → Default → Primary*
 */
export interface DocListSliceDefaultPrimary {
  /**
   * Type field in *DocList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: doc_list.default.primary.type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<
    | "Live reports"
    | "Discoveries"
    | "Interviews"
    | "Press Releases"
    | "Galleries"
    | "All documents"
  >;
}

/**
 * Default variation for DocList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DocListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DocListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DocList*
 */
type DocListSliceVariation = DocListSliceDefault;

/**
 * DocList Shared Slice
 *
 * - **API ID**: `doc_list`
 * - **Description**: DocList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DocListSlice = prismic.SharedSlice<
  "doc_list",
  DocListSliceVariation
>;

/**
 * Item in *Gallery → Default → Primary → Images*
 */
export interface GallerySliceDefaultPrimaryImagesItem {
  /**
   * Image field in *Gallery → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Gallery → Default → Primary*
 */
export interface GallerySliceDefaultPrimary {
  /**
   * Gallery tag field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.gallery_tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  gallery_tag: prismic.KeyTextField;

  /**
   * Images field in *Gallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<GallerySliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice<
  "gallery",
  GallerySliceVariation
>;

/**
 * Primary content in *GalleryLink → Default → Primary*
 */
export interface GalleryLinkSliceDefaultPrimary {
  /**
   * Gallery field in *GalleryLink → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_link.default.primary.gallery
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  gallery: prismic.ContentRelationshipField<"gallery">;
}

/**
 * Default variation for GalleryLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryLinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GalleryLinkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GalleryLink*
 */
type GalleryLinkSliceVariation = GalleryLinkSliceDefault;

/**
 * GalleryLink Shared Slice
 *
 * - **API ID**: `gallery_link`
 * - **Description**: GalleryLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryLinkSlice = prismic.SharedSlice<
  "gallery_link",
  GalleryLinkSliceVariation
>;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Is full-width field in *Image → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image.default.primary.is_fullwidth
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_fullwidth: prismic.BooleanField;

  /**
   * Image width field in *Image → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image_width
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  image_width: prismic.NumberField;

  /**
   * Comment field in *Image → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.comment
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  comment: prismic.KeyTextField;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Item in *ImageGrid → Default → Primary → Item*
 */
export interface ImageGridSliceDefaultPrimaryItemItem {
  /**
   * Image field in *ImageGrid → Default → Primary → Item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.default.primary.item[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ImageGrid → Default → Primary → Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.default.primary.item[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ImageGrid → Default → Primary → Item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.default.primary.item[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ImageGrid → Default → Primary*
 */
export interface ImageGridSliceDefaultPrimary {
  /**
   * Title field in *ImageGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Item field in *ImageGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.default.primary.item[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  item: prismic.GroupField<Simplify<ImageGridSliceDefaultPrimaryItemItem>>;
}

/**
 * Default variation for ImageGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageGrid*
 */
type ImageGridSliceVariation = ImageGridSliceDefault;

/**
 * ImageGrid Shared Slice
 *
 * - **API ID**: `image_grid`
 * - **Description**: ImageGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGridSlice = prismic.SharedSlice<
  "image_grid",
  ImageGridSliceVariation
>;

/**
 * Item in *MemberList → Default → Primary → Members*
 */
export interface ImageListSliceDefaultPrimaryMembersItem {
  /**
   * Member field in *MemberList → Default → Primary → Members*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: image_list.default.primary.members[].member
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  member: prismic.ContentRelationshipField<"author">;
}

/**
 * Primary content in *MemberList → Default → Primary*
 */
export interface ImageListSliceDefaultPrimary {
  /**
   * Members field in *MemberList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_list.default.primary.members[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  members: prismic.GroupField<
    Simplify<ImageListSliceDefaultPrimaryMembersItem>
  >;
}

/**
 * Default variation for MemberList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MemberList*
 */
type ImageListSliceVariation = ImageListSliceDefault;

/**
 * MemberList Shared Slice
 *
 * - **API ID**: `image_list`
 * - **Description**: MemberList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageListSlice = prismic.SharedSlice<
  "image_list",
  ImageListSliceVariation
>;

/**
 * Item in *Purchase → Default → Primary → Links*
 */
export interface PurchaseSliceDefaultPrimaryLinksItem {
  /**
   * Link field in *Purchase → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: purchase.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Purchase → Default → Primary*
 */
export interface PurchaseSliceDefaultPrimary {
  /**
   * CD Cover field in *Purchase → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: purchase.default.primary.cd_cover
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cd_cover: prismic.ImageField<never>;

  /**
   * Title field in *Purchase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: purchase.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Artist field in *Purchase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: purchase.default.primary.artist
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  artist: prismic.KeyTextField;

  /**
   * Release date field in *Purchase → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: purchase.default.primary.release_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  release_date: prismic.DateField;

  /**
   * Links field in *Purchase → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: purchase.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<PurchaseSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for Purchase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PurchaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PurchaseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Purchase*
 */
type PurchaseSliceVariation = PurchaseSliceDefault;

/**
 * Purchase Shared Slice
 *
 * - **API ID**: `purchase`
 * - **Description**: Purchase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PurchaseSlice = prismic.SharedSlice<
  "purchase",
  PurchaseSliceVariation
>;

/**
 * Primary content in *Quote → Default → Primary*
 */
export interface QuoteSliceDefaultPrimary {
  /**
   * Quote field in *Quote → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Author field in *Quote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.default.primary.author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSlice = prismic.SharedSlice<"quote", QuoteSliceVariation>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Title field in *RichText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *Setlist → Default → Primary → Song*
 */
export interface SetlistSliceDefaultPrimarySongItem {
  /**
   * Number field in *Setlist → Default → Primary → Song*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: setlist.default.primary.song[].number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;

  /**
   * Title (EN) field in *Setlist → Default → Primary → Song*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: setlist.default.primary.song[].title_en
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_en: prismic.KeyTextField;

  /**
   * Title (JP) field in *Setlist → Default → Primary → Song*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: setlist.default.primary.song[].title_jp
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_jp: prismic.KeyTextField;

  /**
   * Link field in *Setlist → Default → Primary → Song*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: setlist.default.primary.song[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Setlist → Default → Primary → Encore Song*
 */
export interface SetlistSliceDefaultPrimaryEncoreSongItem {
  /**
   * Title (EN) field in *Setlist → Default → Primary → Encore Song*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: setlist.default.primary.encore_song[].title_en
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_en: prismic.KeyTextField;

  /**
   * Title (JP) field in *Setlist → Default → Primary → Encore Song*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: setlist.default.primary.encore_song[].title_jp
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_jp: prismic.KeyTextField;

  /**
   * Link field in *Setlist → Default → Primary → Encore Song*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: setlist.default.primary.encore_song[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Setlist → Default → Primary*
 */
export interface SetlistSliceDefaultPrimary {
  /**
   * Song field in *Setlist → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: setlist.default.primary.song[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  song: prismic.GroupField<Simplify<SetlistSliceDefaultPrimarySongItem>>;

  /**
   * Encore Song field in *Setlist → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: setlist.default.primary.encore_song[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  encore_song: prismic.GroupField<
    Simplify<SetlistSliceDefaultPrimaryEncoreSongItem>
  >;
}

/**
 * Default variation for Setlist Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SetlistSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SetlistSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Setlist*
 */
type SetlistSliceVariation = SetlistSliceDefault;

/**
 * Setlist Shared Slice
 *
 * - **API ID**: `setlist`
 * - **Description**: Setlist
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SetlistSlice = prismic.SharedSlice<
  "setlist",
  SetlistSliceVariation
>;

/**
 * Item in *Buttons → Default → Primary → Button*
 */
export interface SingleButtonSliceDefaultPrimaryButtonItem {
  /**
   * Link field in *Buttons → Default → Primary → Button*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: single_button.default.primary.button[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Buttons → Default → Primary*
 */
export interface SingleButtonSliceDefaultPrimary {
  /**
   * Title field in *Buttons → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_button.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Buttons → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: single_button.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button field in *Buttons → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: single_button.default.primary.button[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  button: prismic.GroupField<
    Simplify<SingleButtonSliceDefaultPrimaryButtonItem>
  >;
}

/**
 * Default variation for Buttons Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SingleButtonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Buttons*
 */
type SingleButtonSliceVariation = SingleButtonSliceDefault;

/**
 * Buttons Shared Slice
 *
 * - **API ID**: `single_button`
 * - **Description**: SingleButton
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleButtonSlice = prismic.SharedSlice<
  "single_button",
  SingleButtonSliceVariation
>;

/**
 * Item in *SocialLinks → Default → Primary → Links*
 */
export interface SocialLinksSliceDefaultPrimaryLinksItem {
  /**
   * Link field in *SocialLinks → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social_links.default.primary.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *SocialLinks → Default → Primary*
 */
export interface SocialLinksSliceDefaultPrimary {
  /**
   * Links field in *SocialLinks → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: social_links.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<SocialLinksSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for SocialLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialLinksSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SocialLinks*
 */
type SocialLinksSliceVariation = SocialLinksSliceDefault;

/**
 * SocialLinks Shared Slice
 *
 * - **API ID**: `social_links`
 * - **Description**: SocialLinks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialLinksSlice = prismic.SharedSlice<
  "social_links",
  SocialLinksSliceVariation
>;

/**
 * Item in *Taglist → Default → Primary → Tags*
 */
export interface TaglistSliceDefaultPrimaryTagsItem {
  /**
   * Tag field in *Taglist → Default → Primary → Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: taglist.default.primary.tags[].tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Primary content in *Taglist → Default → Primary*
 */
export interface TaglistSliceDefaultPrimary {
  /**
   * Tags field in *Taglist → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: taglist.default.primary.tags[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tags: prismic.GroupField<Simplify<TaglistSliceDefaultPrimaryTagsItem>>;
}

/**
 * Default variation for Taglist Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TaglistSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TaglistSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Taglist*
 */
type TaglistSliceVariation = TaglistSliceDefault;

/**
 * Taglist Shared Slice
 *
 * - **API ID**: `taglist`
 * - **Description**: Taglist
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TaglistSlice = prismic.SharedSlice<
  "taglist",
  TaglistSliceVariation
>;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * Youtube ID field in *Video → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.youtube_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  youtube_id: prismic.KeyTextField;

  /**
   * Caption field in *Video → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticlesDocument,
      ArticlesDocumentData,
      ArticlesDocumentDataSlicesSlice,
      ArticlesDocumentDataSlices1Slice,
      AuthorDocument,
      AuthorDocumentData,
      GalleryDocument,
      GalleryDocumentData,
      GalleryDocumentDataGalleryItem,
      GalleryDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AuthorsSlice,
      AuthorsSliceDefaultPrimary,
      AuthorsSliceVariation,
      AuthorsSliceDefault,
      CarouselSlice,
      CarouselSliceDefaultPrimarySlidesItem,
      CarouselSliceDefaultPrimary,
      CarouselSliceVariation,
      CarouselSliceDefault,
      DocListSlice,
      DocListSliceDefaultPrimary,
      DocListSliceVariation,
      DocListSliceDefault,
      GallerySlice,
      GallerySliceDefaultPrimaryImagesItem,
      GallerySliceDefaultPrimary,
      GallerySliceVariation,
      GallerySliceDefault,
      GalleryLinkSlice,
      GalleryLinkSliceDefaultPrimary,
      GalleryLinkSliceVariation,
      GalleryLinkSliceDefault,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageGridSlice,
      ImageGridSliceDefaultPrimaryItemItem,
      ImageGridSliceDefaultPrimary,
      ImageGridSliceVariation,
      ImageGridSliceDefault,
      ImageListSlice,
      ImageListSliceDefaultPrimaryMembersItem,
      ImageListSliceDefaultPrimary,
      ImageListSliceVariation,
      ImageListSliceDefault,
      PurchaseSlice,
      PurchaseSliceDefaultPrimaryLinksItem,
      PurchaseSliceDefaultPrimary,
      PurchaseSliceVariation,
      PurchaseSliceDefault,
      QuoteSlice,
      QuoteSliceDefaultPrimary,
      QuoteSliceVariation,
      QuoteSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SetlistSlice,
      SetlistSliceDefaultPrimarySongItem,
      SetlistSliceDefaultPrimaryEncoreSongItem,
      SetlistSliceDefaultPrimary,
      SetlistSliceVariation,
      SetlistSliceDefault,
      SingleButtonSlice,
      SingleButtonSliceDefaultPrimaryButtonItem,
      SingleButtonSliceDefaultPrimary,
      SingleButtonSliceVariation,
      SingleButtonSliceDefault,
      SocialLinksSlice,
      SocialLinksSliceDefaultPrimaryLinksItem,
      SocialLinksSliceDefaultPrimary,
      SocialLinksSliceVariation,
      SocialLinksSliceDefault,
      TaglistSlice,
      TaglistSliceDefaultPrimaryTagsItem,
      TaglistSliceDefaultPrimary,
      TaglistSliceVariation,
      TaglistSliceDefault,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
    };
  }
}
