import './globals.css'
import { DM_Sans, Poppins, Noto_Sans_JP } from 'next/font/google'

const DMSans = DM_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'BONJOUR IDOL',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={DMSans.className}>{children}</body>
    </html>
  )
}
