// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  authors: dynamic(() => import("./Authors")),
  carousel: dynamic(() => import("./Carousel")),
  contact_form: dynamic(() => import("./ContactForm")),
  doc_list: dynamic(() => import("./DocList")),
  gallery: dynamic(() => import("./Gallery")),
  image: dynamic(() => import("./Image")),
  image_grid: dynamic(() => import("./ImageGrid")),
  image_list: dynamic(() => import("./MemberList")),
  purchase: dynamic(() => import("./Purchase")),
  quote: dynamic(() => import("./Quote")),
  rich_text: dynamic(() => import("./RichText")),
  setlist: dynamic(() => import("./Setlist")),
  single_button: dynamic(() => import("./Buttons")),
  social_links: dynamic(() => import("./SocialLinks")),
  taglist: dynamic(() => import("./Taglist")),
  video: dynamic(() => import("./Video")),
};
