// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  authors: dynamic(() => import("./Authors")),
  carousel: dynamic(() => import("./Carousel")),
  contact_form: dynamic(() => import("./ContactForm")),
  doc_list: dynamic(() => import("./DocList")),
  image: dynamic(() => import("./Image")),
  image_grid: dynamic(() => import("./ImageGrid")),
  image_list: dynamic(() => import("./MemberList")),
  interview: dynamic(() => import("./Interview")),
  party_about: dynamic(() => import("./PartyAbout")),
  party_lineup: dynamic(() => import("./PartyLineup")),
  party_rules: dynamic(() => import("./PartyRules")),
  party_socials: dynamic(() => import("./PartySocials")),
  purchase: dynamic(() => import("./Purchase")),
  quote: dynamic(() => import("./Quote")),
  rich_text: dynamic(() => import("./RichText")),
  separator: dynamic(() => import("./Separator")),
  setlist: dynamic(() => import("./Setlist")),
  single_button: dynamic(() => import("./Buttons")),
  social_links: dynamic(() => import("./SocialLinks")),
  table_contents: dynamic(() => import("./TableContents")),
  taglist: dynamic(() => import("./Taglist")),
  video: dynamic(() => import("./Video")),
};
